apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: haritejnarayan-com-tls
spec:
  secretName: haritejnarayan-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: haritejnarayan.com
  dnsNames:
    - haritejnarayan.com
    - www.haritejnarayan.com